# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anki_addon_exporter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(550, 320)
        Dialog.setMaximumSize(QtCore.QSize(550, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/picturetopeople.org-78fa7fadd60dc6ffdec28b8183e03d0bddd7b0bf9484bf1b65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit, 0, QtCore.Qt.AlignVCenter)
        self.bt_Broswe = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_Broswe.setObjectName("bt_Broswe")
        self.horizontalLayout.addWidget(self.bt_Broswe)
        self.bt_Default = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_Default.setObjectName("bt_Default")
        self.horizontalLayout.addWidget(self.bt_Default)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_Xport = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_Xport.setObjectName("bt_Xport")
        self.horizontalLayout_2.addWidget(self.bt_Xport)
        self.bt_Copy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_Copy.setObjectName("bt_Copy")
        self.horizontalLayout_2.addWidget(self.bt_Copy)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Anki Add-On Number Exporter"))
        self.label.setText(_translate("Dialog", "Directory:"))
        self.bt_Broswe.setText(_translate("Dialog", "Browse"))
        self.bt_Default.setText(_translate("Dialog", "Default"))
        self.bt_Xport.setText(_translate("Dialog", "Export"))
        self.bt_Copy.setText(_translate("Dialog", "Copy All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
